# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Save Artifact Build release apk 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
#       send to telegram
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.

        
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk 
#       - run: flutter build appbundle
      
#       upload to articact
      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk

#       upload to telegram
      - name: send APK to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: APK Udayana Mobile
          document: build/app/outputs/flutter-apk/app-release.apk

#       upload AAB to telegram
#       - name: send AAB release to telegram
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: AAB Udayana Mobile Releease
#           document: build/app/outputs/bundle/release/app-release.aab
